blog/article/urls.py
from django.urls import path
from article import views


app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
    path('articleRead/<int:articleId>/', views.articleRead, name='articleRead'),
    path('articleUpdate/<int:articleId>/', views.articleUpdate, name='articleUpdate'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
]

blog/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('main/about/', views.about, name='about'),
]

blog/article/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-pubDateTime']



class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.article.title + '-' + str(self.id)
    
    
    class Meta:
        ordering = ['pubDateTime']

blog/article/forms.py
from django import forms
from article.models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'content']

blog/article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from article.models import Article, Comment
from article.forms import ArticleForm

def article(request):
    '''
    Render the article page
    '''
    articles = {article:Comment.objects.filter(article=article) for article in Article.objects.all()}
    context = {'articles':articles}
    return render(request, 'article/article.html', context)

def articleCreate(request):
    '''
    Create a new article instance
        1. If method is GET, render an empty form
        2. If method is POST,
           * validate the form and display error messages if the form is invalid
           * else, save it to the model and redirect to the article page
    '''
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        return render(request, template, {'articleForm':ArticleForm()})
    
    # POST
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})

    articleForm.save()
    messages.success(request, '文章已新增')
    return redirect('article:article')
def articleRead(request, articleId):
    '''
    Read an article
        1. Get the article instance; redirect to the 404 page if not found
        2. Render the articleRead template with the article instance and its
           associated comments
    '''
    article = get_object_or_404(Article, id=articleId)
    context = {
        'article': article,
        'comments': Comment.objects.filter(article=article)
    }
    return render(request, 'article/articleRead.html', context)
def articleUpdate(request, articleId):
    '''
    Update the article instance:
        1. Get the article to update; redirect to 404 if not found
        2. If method is GET, render a bound form
        3. If method is POST,
           * validate the form and render a bound form if the form is invalid
           * else, save it to the model and redirect to the articleRead page
    '''
    article = get_object_or_404(Article, id=articleId)
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        articleForm = ArticleForm(instance=article)
        return render(request, template, {'articleForm':articleForm})

    # POST
    articleForm = ArticleForm(request.POST, instance=article)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})

    articleForm.save()
    messages.success(request, '文章已修改') 
    return redirect('article:articleRead', articleId=articleId)

blog/main/views.py
from django.shortcuts import render



def main(request):
    '''
    Render the main page
    '''
    context = {'like':'Django 很棒'}
    return render(request, 'main/main.html', context)

def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

blog/article/templates/article/article.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}歡迎蒞臨{% endblock %}
{% block content %}
<p><a class="btn" href="{% url 'article:articleCreate' %}">新增文章</a></p>
{% for article, comments in articles.items %}
  <h3><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></h3>
  <p>發表時間：{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
  <div class="articleContent">{{ article.content|linebreaks|truncatechars_html:30 }}</div>
  {% for comment in comments %}
    <div class="commentDiv">
      <span class="comment">{{ comment.content }}</span>
      <br>
      <span class="commentTime">{{ comment.pubDateTime|date:'m月d日 H:i' }}</span>
    </div>
  {% endfor %}
  <hr>
{% endfor %}
{% endblock %}

blog/article/templates/article/articleCreateUpdate.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}
  {% if articleForm.instance.id %}
    修改文章
  {% else %}
    新增文章
  {% endif %}
{% endblock %}
{% block content %}
{% if articleForm.instance.id %}
  <form method="post" action="{% url 'article:articleUpdate' articleForm.instance.id %}">
{% else %}
  <form method="post" action="{% url 'article:articleCreate' %}">
{% endif %}
  {% csrf_token %}
  {{ articleForm.as_p }}
  <input class="btn" type="submit" value="送出">
  <a class="btn" href="{% url 'article:article' %}">放棄</a>
</form>
{% endblock %}

blog/article/templates/article/articleRead.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}閱讀文章{% endblock %}
{% block content %}
<h3 class="inlineBlock">{{ article.title }}</h3>
<a class="btn inlineBlock" href="{% url 'article:articleUpdate' article.id %}">修改</a>
<p>發表時間：{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
<div class="articleContent">{{ article.content|linebreaks }}</div>
{% for comment in comments %}
  <div class="commentDiv">
    <span class="comment">{{ comment.content }}</span>
    <br>
    <span class="commentTime">{{ comment.pubDateTime|date:'Y-m-d H:i'}}</span>
  </div>
{% endfor %}
{% endblock %}

blog/main/templates/main/about.html
{% extends 'main/base.html' %}
{% block heading %}關於{% endblock %}
{% block content %}
<p>歡迎來到我的部落格，您可盡情瀏覽並留言。</p>
{% endblock %}

blog/main/templates/main/base.html
<!doctype html>
{% load static %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
{% block css %}{% endblock %}
</head>
<body>
{% include 'main/menu.html' %}
<h2>部落格 -- {% block heading %}{% endblock %}</h2>
{% for message in messages %}
  <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}
{% block content %}{% endblock %}
</body>
</html>

blog/main/templates/main/main.html
{% extends 'main/base.html' %}
{% block heading %}首頁{% endblock %}
{% block content %}
<p>{{ like }}</p>
{% endblock %}l>

blog/main/templates/main/menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">關於</a></li>
  <li><a href="{% url 'article:article' %}">部落格</a></li>
</ul>